application: whohasthepager
version: 1
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: webapp2
  version: "2.5.1"
  
- name: jinja2
  version: latest

handlers:
- url: /css
  static_dir: stylesheets/

- url: /favicon\.ico
  static_files: dtsp.ico
  upload: favicon\.ico

- url: /.*
  script: pager.app

- url: /test.*
  script: api.app
